const quizzesData = [
  {
    title: 'JavaScript Core & Async Mastery Checkpoint',
    skill: 'JavaScript',
    category: 'Frontend',
    difficulty: 'Intermediate',
    totalPoints: 100,
    passingScore: 70,
    estimatedMinutes: 10,
    questions: [
      {
        question: 'What is the output of `console.log(typeof null)` in JavaScript?',
        options: ['"null"', '"undefined"', '"object"', '"boolean"'],
        correctAnswerIndex: 2,
        explanation: 'In JavaScript, `typeof null` returns `"object"`. This is a legacy quirk dating back to the first implementation of JavaScript.',
        skillSubtopic: 'Data Types',
      },
      {
        question: 'What is the primary difference between `Promise.all()` and `Promise.allSettled()`?',
        options: [
          '`Promise.all` rejects immediately upon the first rejection, whereas `Promise.allSettled` waits for all promises to settle regardless of rejection',
          '`Promise.allSettled` runs promises sequentially on the main thread',
          '`Promise.all` can only handle up to 5 promises concurrently',
          '`Promise.allSettled` automatically retries failed promises up to 3 times',
        ],
        correctAnswerIndex: 0,
        explanation: '`Promise.all` implements fail-fast behavior, while `Promise.allSettled` returns an array of status objects for all completed promises.',
        skillSubtopic: 'Asynchronous Control Flow',
      },
      {
        question: 'How does variable hoisting behave for variables declared with `let` and `const` compared to `var`?',
        options: [
          '`let` and `const` are not hoisted at all',
          '`let` and `const` are hoisted but remain uninitialized in the Temporal Dead Zone (TDZ) until evaluation',
          '`let` is hoisted to the global scope while `const` is hoisted to the file scope',
          '`var` throws a ReferenceError if accessed before declaration',
        ],
        correctAnswerIndex: 1,
        explanation: '`let` and `const` are hoisted to the top of their block scope, but accessing them before their declaration line throws a ReferenceError due to the Temporal Dead Zone.',
        skillSubtopic: 'Scoping & Hoisting',
      },
      {
        question: 'What is the purpose of the `Array.prototype.reduce()` method?',
        options: [
          'To remove all duplicate elements from an array',
          'To filter elements based on a boolean predicate',
          'To execute a reducer function on each element of the array, resulting in a single accumulated output value',
          'To sort array elements in ascending mathematical order',
        ],
        correctAnswerIndex: 2,
        explanation: '`reduce()` iterates through an array passing an accumulator from item to item, transforming the array into any single target value, object, or aggregated structure.',
        skillSubtopic: 'Functional Array Methods',
      },
      {
        question: 'What happens when you use arrow functions regarding the `this` context?',
        options: [
          'Arrow functions create their own dynamic `this` binding at call time',
          'Arrow functions capture the `this` value of the enclosing lexical context where they were defined',
          'Arrow functions bind `this` strictly to `window` or `global`',
          'Arrow functions cannot access outer variables',
        ],
        correctAnswerIndex: 1,
        explanation: 'Arrow functions do not have their own `this`; they retain the `this` value of the enclosing lexical scope.',
        skillSubtopic: 'Lexical Scope & Functions',
      },
    ],
  },
  {
    title: 'React.js Component Architecture & Hooks Assessment',
    skill: 'React.js',
    category: 'Frontend',
    difficulty: 'Intermediate',
    totalPoints: 100,
    passingScore: 70,
    estimatedMinutes: 10,
    questions: [
      {
        question: 'When does the cleanup function returned by `useEffect` execute?',
        options: [
          'Only when the browser window closes',
          'Before the component unmounts and before re-running the effect on dependency change',
          'Synchronously before the initial render starts',
          'Immediately after state is initialized in useState',
        ],
        correctAnswerIndex: 1,
        explanation: 'React runs the cleanup function before the component is removed from the UI and before running the effect on subsequent renders if dependencies change.',
        skillSubtopic: 'Hooks Lifecycle',
      },
      {
        question: 'What is the main benefit of using `useCallback` in React?',
        options: [
          'It caches the calculated return value of an expensive mathematical computation',
          'It returns a memoized version of a callback function that only changes if dependencies change, preventing unnecessary re-renders of optimized child components',
          'It makes asynchronous API requests run twice as fast',
          'It automatically syncs state with LocalStorage',
        ],
        correctAnswerIndex: 1,
        explanation: '`useCallback` caches a function definition between renders, useful when passing callbacks to optimized children that rely on reference equality.',
        skillSubtopic: 'Performance & Memoization',
      },
      {
        question: 'What is the "Rules of Hooks" requirement regarding conditional hook calls?',
        options: [
          'Hooks must always be called inside loops for dynamic rendering',
          'Hooks can only be called inside `if` statements if wrapped in try/catch',
          'Hooks must only be called at the top level of React function components and never inside loops, conditions, or nested functions',
          'Hooks can only be called from vanilla JS utility classes',
        ],
        correctAnswerIndex: 2,
        explanation: 'Calling hooks at the top level guarantees that hooks are called in the exact same order on every render, allowing React to correctly preserve state between calls.',
        skillSubtopic: 'Rules of Hooks',
      },
      {
        question: 'What is the primary difference between controlled and uncontrolled form inputs in React?',
        options: [
          'Controlled inputs store their current value in React state, while uncontrolled inputs maintain their value internally in the DOM via refs',
          'Uncontrolled inputs are deprecated in React 18/19',
          'Controlled inputs do not allow `onChange` listeners',
          'Uncontrolled inputs automatically validate email format with regex',
        ],
        correctAnswerIndex: 0,
        explanation: 'Controlled components have their value driven by React state; uncontrolled components rely on the DOM to store and manage form state via `useRef`.',
        skillSubtopic: 'Form Management',
      },
      {
        question: 'Why should you avoid mutating state directly in React (e.g. `items.push(newItem)`)?',
        options: [
          'It throws an immediate runtime syntax error',
          'React uses shallow object reference equality to detect changes, so direct mutations do not produce a new memory reference and may fail to trigger re-renders',
          'Direct mutations permanently lock browser memory',
          'It deletes the component from the DOM tree',
        ],
        correctAnswerIndex: 1,
        explanation: 'React compares previous and next state references. If you mutate the existing object or array in place, the reference remains identical, so React skips reconciliation.',
        skillSubtopic: 'Immutability & Reconciliation',
      },
    ],
  },
  {
    title: 'Node.js & Express RESTful Backend Checkpoint',
    skill: 'Node.js',
    category: 'Backend',
    difficulty: 'Intermediate',
    totalPoints: 100,
    passingScore: 70,
    estimatedMinutes: 10,
    questions: [
      {
        question: 'How does Node.js achieve high concurrency despite executing JavaScript on a single thread?',
        options: [
          'By using OS threads for each incoming HTTP request',
          'Through its non-blocking event loop and delegating asynchronous I/O tasks to libuv background worker threads',
          'By compiling all JavaScript into synchronous C++ binaries',
          'By limiting each user session to 10 milliseconds',
        ],
        correctAnswerIndex: 1,
        explanation: 'Node.js uses the libuv library to handle asynchronous I/O operations via system kernel mechanisms and thread pools, keeping the main JS thread non-blocking.',
        skillSubtopic: 'Event Loop & Libuv',
      },
      {
        question: 'In Express.js, what is the required signature for an error-handling middleware function?',
        options: [
          '`(req, res, next)`',
          '`(err, req, res, next)` with exactly 4 parameters',
          '`(err, res)`',
          '`(error, callback)`',
        ],
        correctAnswerIndex: 1,
        explanation: 'Express identifies error-handling middleware specifically by looking for a function with four arguments: `(err, req, res, next)`.',
        skillSubtopic: 'Error Middleware',
      },
      {
        question: 'Which HTTP method should be used for an idempotent operation that completely replaces an existing resource?',
        options: ['POST', 'PUT', 'PATCH', 'CONNECT'],
        correctAnswerIndex: 1,
        explanation: '`PUT` is designed to be idempotent and replaces the complete resource representation at the target URL.',
        skillSubtopic: 'REST Principles',
      },
      {
        question: 'What is the purpose of `express.json()` middleware?',
        options: [
          'To encrypt JSON output sent to the client',
          'To parse incoming request bodies with JSON payloads and populate `req.body`',
          'To format MongoDB documents into JSON schema',
          'To convert HTML into JSON strings',
        ],
        correctAnswerIndex: 1,
        explanation: '`express.json()` is built-in middleware that parses incoming HTTP requests with `Content-Type: application/json` and places the parsed object into `req.body`.',
        skillSubtopic: 'Body Parsing',
      },
      {
        question: 'Why should environment secrets (like JWT_SECRET and DB connection strings) never be committed to Git?',
        options: [
          'Git repositories will fail to compile',
          'Public or shared repositories expose credentials to unauthorized access, compromising database and user data integrity',
          'Because Node.js cannot read `.env` files from Git history',
          'It slows down git push speeds',
        ],
        correctAnswerIndex: 1,
        explanation: 'Committing secrets compromises production security, allowing attackers to access databases, sign fraudulent JWT tokens, or hijack services.',
        skillSubtopic: 'Security Best Practices',
      },
    ],
  },
  {
    title: 'REST APIs & Architecture Checkpoint',
    skill: 'REST APIs',
    category: 'Backend',
    difficulty: 'Intermediate',
    totalPoints: 100,
    passingScore: 70,
    estimatedMinutes: 10,
    questions: [
      {
        question: 'What does idempotency mean in the context of REST APIs?',
        options: [
          'An operation that always executes in less than 50ms',
          'An HTTP method where making multiple identical requests has the same effect on the server as making a single request (e.g. GET, PUT, DELETE)',
          'An endpoint that only accepts XML payloads',
          'An API that requires no authentication',
        ],
        correctAnswerIndex: 1,
        explanation: 'Idempotency means that N > 0 identical requests produce the same side-effect on server state as 1 request.',
        skillSubtopic: 'HTTP Verbs & Idempotency',
      },
      {
        question: 'Which HTTP status code is most appropriate after a resource has been successfully created via POST?',
        options: ['200 OK', '201 Created', '204 No Content', '301 Moved Permanently'],
        correctAnswerIndex: 1,
        explanation: 'HTTP 201 Created signifies that the request succeeded and led to the creation of a new resource.',
        skillSubtopic: 'Status Codes',
      },
      {
        question: 'What is the primary difference between PUT and PATCH methods?',
        options: [
          'PUT replaces the full resource representation, while PATCH applies partial modifications to a resource',
          'PATCH cannot be used with JSON payloads',
          'PUT is only used for image uploads',
          'There is no difference in modern REST',
        ],
        correctAnswerIndex: 0,
        explanation: 'PUT requires the complete replacement of a resource document, whereas PATCH modifies only the specified subset of fields.',
        skillSubtopic: 'REST Methods',
      },
      {
        question: 'What is the purpose of the `Accept` header sent in client HTTP requests?',
        options: [
          'To provide basic auth credentials',
          'To inform the server which content types / MIME formats the client is capable of understanding in the response',
          'To set cookie expiration dates',
          'To enable gzip compression automatically',
        ],
        correctAnswerIndex: 1,
        explanation: 'The `Accept` header is used by HTTP clients to tell the server what media types they accept for the response (content negotiation).',
        skillSubtopic: 'Content Negotiation',
      },
      {
        question: 'Why is the Statelessness constraint beneficial for scaling RESTful API microservices?',
        options: [
          'Because servers do not need to store client session state in memory, allowing any incoming request to be handled by any server instance behind a load balancer',
          'Because it eliminates the need for database storage',
          'Because it forces all clients to use websockets',
          'Because it reduces JavaScript bundle size',
        ],
        correctAnswerIndex: 0,
        explanation: 'Stateless servers can scale horizontally effortlessly because any server replica can process any incoming request without sharing session memory.',
        skillSubtopic: 'Scalability & Architecture',
      },
    ],
  },
];

module.exports = quizzesData;
