const resourcesData = [
  // 1. JavaScript
  {
    title: 'JavaScript: The Hard Parts of Asynchronous JS',
    description: 'Deep dive into the JavaScript Event Loop, microtask queues, execution contexts, closures, and Promises with Will Sentance.',
    type: 'Course',
    url: 'https://frontendmasters.com/courses/javascript-hard-parts-v2/',
    provider: 'Frontend Masters',
    skills: ['JavaScript'],
    difficulty: 'Intermediate',
    duration: '6 hours',
    estimatedHours: 6,
    rating: 4.9,
    tags: ['async', 'closures', 'event-loop', 'es6'],
    prerequisites: ['HTML & CSS'],
    learningStyle: 'Hands-on Projects',
    projectBased: true,
    free: false,
    likesCount: 1420,
  },
  {
    title: 'Modern JavaScript from the Beginning (ES6+)',
    description: 'Master modern pure JavaScript without frameworks: fetch API, DOM manipulation, async/await, and OOP.',
    type: 'Course',
    url: 'https://www.udemy.com/course/modern-javascript-from-the-beginning/',
    provider: 'Udemy',
    skills: ['JavaScript'],
    difficulty: 'Beginner',
    duration: '21 hours',
    estimatedHours: 20,
    rating: 4.8,
    tags: ['fundamentals', 'es6', 'dom'],
    prerequisites: ['HTML & CSS'],
    learningStyle: 'Video',
    projectBased: true,
    free: false,
    likesCount: 980,
  },
  {
    title: 'You Don\'t Know JS Yet: Scope & Closures',
    description: 'An open-source deep dive book on how lexical scope, hoisting, and closures work under the hood in JavaScript engines.',
    type: 'Article',
    url: 'https://github.com/getify/You-Dont-Know-JS',
    provider: 'Kyle Simpson',
    skills: ['JavaScript'],
    difficulty: 'Intermediate',
    duration: '4 hours',
    estimatedHours: 4,
    rating: 4.9,
    tags: ['reading', 'deep-dive', 'closures'],
    prerequisites: ['JavaScript'],
    learningStyle: 'Reading',
    projectBased: false,
    free: true,
    likesCount: 3100,
  },

  // 2. React.js
  {
    title: 'Epic React: Custom Hooks & State Reconciliation',
    description: 'Master advanced React architecture: compound components, state reducers, performance memoization (useMemo/useCallback), and Suspense.',
    type: 'Course',
    url: 'https://epicreact.dev/',
    provider: 'Kent C. Dodds',
    skills: ['React.js'],
    difficulty: 'Intermediate',
    duration: '10 hours',
    estimatedHours: 10,
    rating: 4.9,
    tags: ['react', 'hooks', 'architecture'],
    prerequisites: ['JavaScript'],
    learningStyle: 'Hands-on Projects',
    projectBased: true,
    free: false,
    likesCount: 2200,
  },
  {
    title: 'Official React 18/19 Documentation & Interactive Sandbox',
    description: 'Interactive component state tutorials, thinking in React, declarative UI principles, and modern Server Component foundations.',
    type: 'Documentation',
    url: 'https://react.dev/',
    provider: 'Meta Open Source',
    skills: ['React.js'],
    difficulty: 'Beginner',
    duration: '5 hours',
    estimatedHours: 5,
    rating: 4.9,
    tags: ['react', 'official', 'interactive'],
    prerequisites: ['JavaScript'],
    learningStyle: 'Reading',
    projectBased: false,
    free: true,
    likesCount: 4500,
  },

  // 3. Node.js & Express
  {
    title: 'Node.js, Express & MongoDB Masterclass: RESTful APIs',
    description: 'Build enterprise-grade REST APIs from scratch with JWT authentication, custom middleware, rate limiting, and MongoDB aggregation pipelines.',
    type: 'Course',
    url: 'https://www.udemy.com/course/nodejs-express-mongodb-bootcamp/',
    provider: 'Jonas Schmedtmann',
    skills: ['Node.js', 'Express.js', 'MongoDB', 'REST APIs'],
    difficulty: 'Intermediate',
    duration: '42 hours',
    estimatedHours: 35,
    rating: 4.9,
    tags: ['node', 'express', 'rest-api', 'jwt'],
    prerequisites: ['JavaScript'],
    learningStyle: 'Hands-on Projects',
    projectBased: true,
    free: false,
    likesCount: 5100,
  },
  {
    title: 'Production Ready Express.js API Design Guide',
    description: 'Comprehensive best practices for organizing Express route controllers, async middleware error handling, and security hardening.',
    type: 'Article',
    url: 'https://github.com/goldbergyoni/nodebestpractices',
    provider: 'Node.js Best Practices Community',
    skills: ['Node.js', 'Express.js', 'REST APIs'],
    difficulty: 'Intermediate',
    duration: '3 hours',
    estimatedHours: 3,
    rating: 4.8,
    tags: ['architecture', 'best-practices', 'security'],
    prerequisites: ['Express.js'],
    learningStyle: 'Reading',
    projectBased: false,
    free: true,
    likesCount: 1800,
  },

  // 4. MongoDB & Databases
  {
    title: 'MongoDB University: Data Modeling & Aggregations',
    description: 'Official MongoDB course covering 1-to-N relationships, embedding vs referencing tradeoffs, compound indexes, and multi-stage $facet aggregations.',
    type: 'Course',
    url: 'https://learn.mongodb.com/',
    provider: 'MongoDB University',
    skills: ['MongoDB'],
    difficulty: 'Intermediate',
    duration: '8 hours',
    estimatedHours: 8,
    rating: 4.8,
    tags: ['nosql', 'indexes', 'aggregation'],
    prerequisites: ['Node.js'],
    learningStyle: 'Hands-on Projects',
    projectBased: true,
    free: true,
    likesCount: 2900,
  },

  // 5. REST APIs & Security
  {
    title: 'RESTful API Design & HTTP Status Code Specification',
    description: 'Learn REST constraints: statelessness, idempotency, content negotiation, pagination patterns, and hypermedia controls.',
    type: 'Documentation',
    url: 'https://restfulapi.net/',
    provider: 'REST API Tutorial',
    skills: ['REST APIs'],
    difficulty: 'Intermediate',
    duration: '3 hours',
    estimatedHours: 3,
    rating: 4.7,
    tags: ['http', 'status-codes', 'idempotency'],
    prerequisites: ['Node.js'],
    learningStyle: 'Reading',
    projectBased: false,
    free: true,
    likesCount: 1100,
  },
  {
    title: 'JWT Authentication & Security Hardening Workshop',
    description: 'Complete guide to access and refresh tokens, HTTP-only cookies, bcrypt salt hashing, CORS configuration, and RBAC middleware in Express.',
    type: 'Video',
    url: 'https://www.youtube.com/watch?v=mbsmsi7l3r4',
    provider: 'Web Dev Simplified',
    skills: ['Authentication & Security', 'Node.js', 'Express.js'],
    difficulty: 'Intermediate',
    duration: '2 hours',
    estimatedHours: 2,
    rating: 4.9,
    tags: ['jwt', 'cookies', 'security', 'bcrypt'],
    prerequisites: ['Express.js'],
    learningStyle: 'Video',
    projectBased: true,
    free: true,
    likesCount: 3800,
  },

  // 6. Docker & Deployment
  {
    title: 'Docker & Kubernetes: The Practical Guide',
    description: 'Containerize full-stack MERN apps, multi-stage Dockerfiles, Docker Compose networking, volumes, and deployment on AWS/Render.',
    type: 'Course',
    url: 'https://academind.com/courses/docker-kubernetes',
    provider: 'Academind',
    skills: ['Docker & Deployment'],
    difficulty: 'Advanced',
    duration: '23 hours',
    estimatedHours: 20,
    rating: 4.9,
    tags: ['docker', 'compose', 'devops'],
    prerequisites: ['Node.js'],
    learningStyle: 'Hands-on Projects',
    projectBased: true,
    free: false,
    likesCount: 3400,
  },
];

module.exports = resourcesData;
