const skillsData = [
  // Frontend
  {
    name: 'HTML & CSS',
    category: 'Frontend',
    description: 'Semantic HTML5 markup, CSS3 box model, flexbox, CSS grid, and responsive layouts.',
    difficulty: 'Beginner',
    prerequisites: [],
    relatedSkills: ['Tailwind CSS', 'JavaScript'],
    rolesTargeted: ['Frontend Developer', 'Full Stack Developer'],
    importanceWeight: 0.9,
  },
  {
    name: 'JavaScript',
    category: 'Frontend',
    description: 'Core ES6+ syntax, scope, closures, prototypes, asynchronous control flow, Promises, and Event Loop.',
    difficulty: 'Intermediate',
    prerequisites: ['HTML & CSS'],
    relatedSkills: ['React.js', 'Node.js', 'TypeScript'],
    rolesTargeted: ['Frontend Developer', 'Backend Developer', 'Full Stack Developer'],
    importanceWeight: 1.0,
  },
  {
    name: 'React.js',
    category: 'Frontend',
    description: 'Component architecture, JSX, custom hooks, Virtual DOM reconciliation, Context API, and state immutability.',
    difficulty: 'Intermediate',
    prerequisites: ['JavaScript', 'HTML & CSS'],
    relatedSkills: ['Redux', 'Next.js', 'Tailwind CSS'],
    rolesTargeted: ['Frontend Developer', 'Full Stack Developer'],
    importanceWeight: 1.0,
  },
  {
    name: 'Tailwind CSS',
    category: 'Frontend',
    description: 'Utility-first CSS framework for rapid modern UI development, glassmorphism, and responsive breakpoints.',
    difficulty: 'Beginner',
    prerequisites: ['HTML & CSS'],
    relatedSkills: ['React.js'],
    rolesTargeted: ['Frontend Developer', 'Full Stack Developer'],
    importanceWeight: 0.8,
  },
  {
    name: 'TypeScript',
    category: 'Frontend',
    description: 'Static type checking, interfaces, generics, union types, and enhanced IDE developer velocity.',
    difficulty: 'Intermediate',
    prerequisites: ['JavaScript'],
    relatedSkills: ['React.js', 'Node.js'],
    rolesTargeted: ['Frontend Developer', 'Full Stack Developer'],
    importanceWeight: 0.85,
  },

  // Backend
  {
    name: 'Node.js',
    category: 'Backend',
    description: 'V8 runtime, non-blocking I/O event loop, libuv threadpool, buffer streams, and CommonJS/ESM modules.',
    difficulty: 'Intermediate',
    prerequisites: ['JavaScript'],
    relatedSkills: ['Express.js', 'REST APIs', 'MongoDB'],
    rolesTargeted: ['Backend Developer', 'Full Stack Developer'],
    importanceWeight: 1.0,
  },
  {
    name: 'Express.js',
    category: 'Backend',
    description: 'Minimalist web framework for Node.js, middleware pipelines, dynamic routing, and error handling.',
    difficulty: 'Beginner',
    prerequisites: ['Node.js'],
    relatedSkills: ['REST APIs', 'Authentication & Security'],
    rolesTargeted: ['Backend Developer', 'Full Stack Developer'],
    importanceWeight: 0.95,
  },
  {
    name: 'REST APIs',
    category: 'Backend',
    description: 'RESTful architecture principles, HTTP verbs, status codes, payload formatting, idempotency, and CRUD endpoints.',
    difficulty: 'Intermediate',
    prerequisites: ['Express.js'],
    relatedSkills: ['Node.js', 'MongoDB'],
    rolesTargeted: ['Backend Developer', 'Full Stack Developer'],
    importanceWeight: 0.95,
  },
  {
    name: 'Authentication & Security',
    category: 'Backend',
    description: 'JWT token lifecycles, HTTP-only cookies, bcrypt hashing, CSRF/XSS mitigations, CORS, and RBAC authorization.',
    difficulty: 'Intermediate',
    prerequisites: ['Express.js', 'Node.js'],
    relatedSkills: ['REST APIs'],
    rolesTargeted: ['Backend Developer', 'Full Stack Developer'],
    importanceWeight: 0.9,
  },

  // Database
  {
    name: 'MongoDB',
    category: 'Database',
    description: 'NoSQL document modeling, BSON structure, Mongoose ODM schemas, compound indexes, and aggregation pipelines.',
    difficulty: 'Intermediate',
    prerequisites: ['Node.js'],
    relatedSkills: ['Express.js', 'REST APIs'],
    rolesTargeted: ['Backend Developer', 'Full Stack Developer'],
    importanceWeight: 0.9,
  },
  {
    name: 'PostgreSQL & SQL',
    category: 'Database',
    description: 'Relational schema design, normalization, ACID transactions, complex joins, and SQL query optimization.',
    difficulty: 'Intermediate',
    prerequisites: [],
    relatedSkills: ['Node.js', 'Database'],
    rolesTargeted: ['Backend Developer', 'Full Stack Developer'],
    importanceWeight: 0.85,
  },

  // DevOps & Cloud
  {
    name: 'Git & GitHub',
    category: 'DevOps & Cloud',
    description: 'Version control branching workflows, merge conflict resolution, pull request code reviews, and git CLI mastery.',
    difficulty: 'Beginner',
    prerequisites: [],
    relatedSkills: [],
    rolesTargeted: ['Frontend Developer', 'Backend Developer', 'Full Stack Developer'],
    importanceWeight: 0.8,
  },
  {
    name: 'Docker & Deployment',
    category: 'DevOps & Cloud',
    description: 'Containerization, Dockerfile multi-stage builds, Docker Compose orchestration, and cloud deployment.',
    difficulty: 'Advanced',
    prerequisites: ['Node.js'],
    relatedSkills: ['System Design'],
    rolesTargeted: ['Backend Developer', 'Full Stack Developer', 'DevOps Engineer'],
    importanceWeight: 0.75,
  },
];

module.exports = skillsData;
